/**
 * Generated by scripts/sync.ts from packages/shared/src/deployments.json and
 * packages/shared/src/abi.ts. Do not edit: update the deployment record, then run `pnpm sync`.
 */

import type { NetworkInfo } from "./model.js";

/** Every network in the deployment record, by chain id. Addresses are lowercase. */
export const NETWORKS: Readonly<Record<number, NetworkInfo>> = {
  143: {
    name: "Monad",
    startBlock: 110186397,
    hub: "0x184c6c26c1cb7f79885ed7c71e810e564ceec6a0",
    charger: "0xc555dbb7059b46fa4d3de4b6602e3c52caccff03",
    forwarder: "0x76c9cf548b4179f8901cda1f8623568b58215e62",
    simulationForwarder: "0x9ef6468c5f37b976e57d52054c693269479a784d",
    assets: {
      "0x00000000efe302beaa2b3e6e1b18d08d69a9012a": "AUSD",
      "0x754704bc059f8c67012fed69bc8a327a5aafb603": "USDC",
    },
    rpcUrl: "https://rpc.monad.xyz",
  },
  10143: {
    name: "Monad Testnet",
    startBlock: 67841535,
    hub: "0x08ca57f960d5d9a2b06475c6ca4583eda4680bc1",
    charger: "0xb4333c519c9d5c300737824ca5792891dbba9e03",
    forwarder: "0xf8344cfd5c43616a4366c34e3eee75af79a74482",
    simulationForwarder: "0xb9f79d863261869b234c481d1f9a7af84aead192",
    assets: {
      "0x534b2f3a21130d7a60830c2df862319e593943a3": "USDC",
      "0xf3066908dabe11f2e72f6887d9943eeb621a0eb9": "tAUSD",
    },
    rpcUrl: "https://testnet-rpc.monad.xyz",
  },
};

/** Revert selectors a batch charge can report, with the error each one is. */
export const REVERT_REASONS: Readonly<Record<string, string>> = {
  "0x08c379a0": "Error(string)",
  "0x0f5feab6": "NotDue(uint64,uint256)",
  "0x17479ac8": "InvalidPeriod()",
  "0x1c26714c": "InsufficientGas()",
  "0x2c5211c6": "InvalidAmount()",
  "0x2f2938ce": "InvalidAction(uint8)",
  "0x305a27a9": "StringTooLong(string)",
  "0x3ee5aeb5": "ReentrancyGuardReentrantCall()",
  "0x473251f4": "UnknownMandate()",
  "0x4e487b71": "Panic(uint256)",
  "0x5274afe7": "SafeERC20FailedOperation(address)",
  "0x5592f1b2": "NotForwarder(address)",
  "0x6dfcc650": "SafeCastOverflowedUintDowncast(uint8,uint256)",
  "0x6f79c78a": "InvalidAsset(address)",
  "0x73eb681e": "InvalidTotalCap()",
  "0x77896a1a": "MandateExpired(uint64,uint256)",
  "0x86802683": "NotStreaming()",
  "0x8baa579f": "InvalidSignature()",
  "0x976bd764": "TotalCapExceeded(uint96,uint96)",
  "0xaf7301ae": "InvalidVault(address)",
  "0xb0f4185d": "MandateIsCancelled()",
  "0xb3512b0c": "InvalidShortString()",
  "0xb93ce888": "PaymentMismatch(uint256,uint256)",
  "0xc0b6c919": "InvalidMerchant()",
  "0xd36c8500": "InvalidExpiry()",
  "0xdd58e456": "MandateIsPaused()",
  "0xdda424b6": "MandateNotPaused()",
  "0xe44e2160": "InvalidHub()",
  "0xe90aded4": "NonceAlreadyUsed(address,uint256)",
  "0xea8e4eb5": "NotAuthorized()",
  "0xf58e0a14": "InvalidChargeCap()",
  "0xf88f0490": "SignatureExpired(uint256,uint256)",
};
